apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://auth-service:3001"
        - name: REACT_APP_AUTH_API_URL
          value: "http://auth-service:3001"
        - name: REACT_APP_RESTAURANT_API_URL
          value: "http://restaurant-service:3002"
        - name: REACT_APP_ORDER_API_URL
          value: "http://order-service:3003"
        - name: REACT_APP_DELIVERY_API_URL
          value: "http://delivery-service:3004"
        - name: REACT_APP_PAYMENT_API_URL
          value: "http://payment-service:3005"
        - name: REACT_APP_ADMIN_API_URL
          value: "http://admin-service:3006"
